[reframe]
name = "Nuchain Dapp"
author = "somebody"
min_version = "0.3.0"

[project]
name = "Nuchain Dapp"
version = "0.1.0"
ignore_dirs = [
    "target", "build"
]

finish_text = """Usage:

    $ cd $name_kebab_case$/backend

Test:

    $ cargo +nightly test

Build:

    $ cargo +nightly contract build

    NOTES: Please make sure you have cargo-contract installed,
           or install with the following command:

           $ cargo install cargo-contract --vers 0.8.0 --force --locked
"""

[[param]]
description = { ask = "Description ?", default = "My cool Nuchain Dapp description here" }

[[param]]
author_name = { ask = "Author name?", default="Author" }

[[param]]
author_email = { ask = "Author email?", default="author@example.com" }

[[param]]
with_failed_event = { ask = "Emit event when failed?", default="true" }
